# Pre-commit hooks configuration for NeuroScope - Simplified for offline use
repos:
  # Local hooks only - no internet required
  - repo: local
    hooks:
      # Black code formatter
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
        args: ["--line-length=88"]
        
      # isort import organizer  
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types_or: [cython, pyi, python]
        args: ["--filter-files", "--profile", "black", "--line-length=88"]
        
      # Flake8 linter - uses .flake8 config file
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true

