# Pre-commit hooks configuration for NeuroScope
repos:
  # General code quality hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: debug-statements
      - id: check-docstring-first

  # Local hooks using system dependencies
  - repo: local
    hooks:
      # Black code formatter
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
        
      # isort import organizer  
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types_or: [cython, pyi, python]
        args: ["--filter-files", "--profile", "black"]
        
      # Flake8 linter
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
        
      # Bandit security linter
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
        require_serial: true
        args: ["-c", "bandit.yml"]
        
      # MyPy type checker
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true
        args: [--strict]
        
      # PyUpgrade syntax upgrader
      - id: pyupgrade
        name: pyupgrade
        description: Automatically upgrade syntax for newer versions.
        entry: pyupgrade
        language: system
        types: [python]
        args: [--py312-plus]
        
      # Pytest test runner
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["-v", "--tb=short", "--cov=neuroscope"]

  # Prettier for markdown and other files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [markdown, yaml, json]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
