# Test Release to TestPyPI
name: Test Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Test version (e.g., 0.1.0a1, 0.1.0b1, 0.1.0rc1, 0.1.0.dev1)'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  test-build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1

    - name: Install dependencies
      run: poetry install --with dev

    - name: Set version
      id: version
      run: |
        VERSION="${{ github.event.inputs.version }}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Update version in pyproject.toml
      run: |
        poetry version ${{ steps.version.outputs.version }}

    - name: Run tests
      run: poetry run nox -s tests

    - name: Run quality checks
      run: |
        poetry run nox -s lint
        poetry run nox -s mypy

    - name: Build package
      run: poetry build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-dist
        path: dist/

  testpypi-release:
    needs: test-build
    runs-on: ubuntu-latest
    environment: testpypi
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: test-dist
        path: dist/

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TESTPYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        packages-dir: dist/

    - name: Test installation from TestPyPI
      run: |
        sleep 60  # Wait for package to be available
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ neuroscope==${{ needs.test-build.outputs.version }}
        python -c "import neuroscope; print(f'✅ TestPyPI package works! Version: {neuroscope.__version__}')"
